#!/bin/bash
# File generated by ocamlbuild

cd /home/stephane/Documents/LRS/projet/Lusmodelchecker/lmoch/src/
# rm -f *.ml~
rm -f *.*~
# Also clean the script itself Optionel
# rm -f /home/stephane/Documents/Ocaml/Chapter2/_build/sanitize.sh
